<div id="b_products_manager" class="">
    <div class="buttons_box">
      <table>
        <tr>
          <td>
            <span class="search_label">
            Search by Product Name:
            </span>
          </td>
          <td>
            <input type="text" class="input-text no-changes" value="" id="productGrid_product_filter_search" name="search">
            <button style="" class="scalable task" type="button" id="id_search_button"><span>Search</span></button>
          </td>
        </tr>
        <tr>
          <td>
            <span class="search_label">
            Search by SKU:
            </span>
          </td>
          <td>
            <input type="text" class="input-text no-changes" value="" id="productGrid_sku_filter_search" name="search">
            <button style="" class="scalable task" type="button" id="id_search_sku_button"><span>Search</span></button>
          </td>
        </tr>
        <tr>
          <td></td>
          <td>
          </td>
        </tr>
      </table>
      <div class="update_qty">
            <button style="" class="scalable task" type="button" id="id_update_qty_button"><span>Update Qty</span></button>
      </div>
    </div>
    <div id="b_product_results"></div>
</div>

<script>
    var ajaxImgUrl = '<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif'); ?>';
    var productsScreenUrl = '<?php echo Mage::helper("adminhtml")->getUrl("productsmanager/adminhtml_products/index") ?>';

    /**
     * Search by product name
     **/
    jQuery('button#id_search_button').click(function(){
        jQuery('#loading-mask').css('display', 'block');
        jQuery('#b_product_results').load(
            productsScreenUrl + '?search=' + jQuery('#productGrid_product_filter_search').val(), 
            function() {
                jQuery('#loading-mask').css('display', 'none')
            }); 
    });

    /**
     * Search by SKU
     **/
    jQuery('button#id_search_sku_button').click(function(){
        jQuery('#loading-mask').css('display', 'block');
        jQuery('#b_product_results').load(
            productsScreenUrl + '?search_sku=' + jQuery('#productGrid_sku_filter_search').val(), 
            function() {
                jQuery('#loading-mask').css('display', 'none')
            }); 
    });

    /**
     * Update Qty
     **/
    jQuery('button#id_update_qty_button').click(function(){
        jQuery('#loading-mask').css('display', 'block');
        jQuery('#products_update_form').ajaxSubmit({
          success: function(){
            jQuery('#loading-mask').css('display', 'none');
          }
        });
    });
</script>
